package com.nuggeta.ngdl;
import com.nuggeta.ngdl.nobjects.PublishFriendThirdPartyMessageResponse;
import com.nuggeta.ngdl.nobjects.PublishFriendThirdPartyMessageResponse;

interface PublishFriendThirdPartyMessageResponseHandler
{

	function onPublishFriendThirdPartyMessageResponse( publishfriendthirdpartymessageresponse:PublishFriendThirdPartyMessageResponse):Void;
}
